# Quickstart for GitHub Actions
# https://docs.github.com/en/actions/quickstart

name: CI
on: [ push, pull_request, workflow_dispatch ]
jobs:
  test:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    name: Test on JDK ${{ matrix.java }} OS ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        java: [ 8, 11, 17 ]
      fail-fast: false
      max-parallel: 64

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
          cache: maven
      - run: ./mvnw -V --no-transfer-progress clean package
      # https://github.com/marketplace/actions/codecov
      - uses: codecov/codecov-action@v3
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
